
title: Namlete #Your awesome title
email: nguyenlenam15082007@gmailcom
description: Tạo blog cho vui chứ không gì cả. 


baseurl: # the subpath of the site
url: https://namle-a6.github.io/Namlete.github.io/ # the base hostname & protocol for your site

permalink: /:year-:month/:title
timezone: Asia/Ho Chi Minh City

favicon: /assets/img/favicon.ico

google_analytics: #UA—XXXXXXXX-X
disqus_shortname: #disqus shortname
cusdis:
    app_id: #your cusdis app_id

# Page views settings
pageviews:
  provider: # now only supports 'goatcounter'

user:
  name: Namlete
  pic: /assets/img/Jirô Horikoshi.jpg
  picAlt: "Jirô Horikoshi"
  job: một thằng lông bông sinh năm 2007
  aboutme: true # comment this out if you don't need the 'about' page.

exclude:
  - README.md
  - LICENSE
  - github

defaults:
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comment: true   

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown 

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false
